"""FastAPI service for the APIx series.

Every response carries provenance: which sources contributed, how much of the
basket was observed rather than imputed, and - critically - whether any of the
underlying quotes were synthetic. A consumer of this API can always tell
whether they are looking at a statistic or a demo.
"""
from __future__ import annotations

from datetime import date
from pathlib import Path
from typing import Optional

from fastapi import FastAPI, HTTPException, Query
from fastapi.responses import HTMLResponse, JSONResponse

from ..config import load_basket, load_sources
from ..db import connect, load_index

DB_PATH = "data/apix.db"
DASHBOARD = Path(__file__).resolve().parent.parent / "dashboard" / "index.html"

app = FastAPI(
    title="APIx - Real-time Airfare Price Index",
    version="0.1.0",
    description="Prototype airfare price index for the CPI Transport sub-group.",
)


def _synthetic_flag(conn) -> bool:
    row = conn.execute(
        "SELECT COUNT(*) n FROM cell_price WHERE source_id LIKE 'sim_%'"
    ).fetchone()
    return bool(row and row["n"])


def _provenance(conn) -> dict:
    rows = conn.execute(
        "SELECT source_id, COUNT(*) n, MIN(collected_on) f, MAX(collected_on) l "
        "FROM cell_price GROUP BY source_id ORDER BY n DESC"
    ).fetchall()
    return {
        "synthetic": _synthetic_flag(conn),
        "sources": [
            {"source_id": r["source_id"], "cell_days": r["n"], "first": r["f"], "last": r["l"]}
            for r in rows
        ],
    }


@app.get("/health")
def health():
    with connect(DB_PATH) as conn:
        n = conn.execute("SELECT COUNT(*) c FROM index_point").fetchone()["c"]
        prov = _provenance(conn)
    return {"status": "ok", "index_points": n, **prov}


@app.get("/index/{frequency}")
def index_series(
    frequency: str,
    start: Optional[date] = Query(None),
    end: Optional[date] = Query(None),
    include_failed: bool = Query(False, description="include points whose quality is 'fail'"),
):
    if frequency not in ("daily", "weekly", "monthly"):
        raise HTTPException(400, "frequency must be daily, weekly or monthly")
    with connect(DB_PATH) as conn:
        rows = load_index(conn, frequency)
        prov = _provenance(conn)
    if start:
        rows = [r for r in rows if date.fromisoformat(r["on_date"]) >= start]
    if end:
        rows = [r for r in rows if date.fromisoformat(r["on_date"]) <= end]
    if not include_failed:
        rows = [r for r in rows if r["quality"] != "fail"]

    body = {
        "frequency": frequency,
        "base_period": load_basket().meta["base_period"],
        "base_value": load_basket().base_value,
        "n": len(rows),
        "provenance": prov,
        "series": rows,
    }
    if prov["synthetic"]:
        body["WARNING"] = (
            "This series is computed from SYNTHETIC quotes generated by "
            "apix.collect.simulator. It is a pipeline demonstration and must not "
            "be cited as a measurement of airfare inflation."
        )
    return JSONResponse(body)


def _rows(frequency: str, include_failed: bool = False) -> list[dict]:
    """Plain accessor shared by the endpoints. Endpoint functions must not call
    each other - FastAPI's Query defaults are objects, not values, outside a
    request."""
    if frequency not in ("daily", "weekly", "monthly"):
        raise HTTPException(400, "frequency must be daily, weekly or monthly")
    with connect(DB_PATH) as conn:
        rows = load_index(conn, frequency)
    return rows if include_failed else [r for r in rows if r["quality"] != "fail"]


@app.get("/inflation/{frequency}")
def inflation(frequency: str, periods: int = Query(1, ge=1)):
    """Period-over-period change, the number a policy user actually wants."""
    rows = _rows(frequency)
    if len(rows) <= periods:
        raise HTTPException(404, "not enough points")
    out = []
    for prev, cur in zip(rows, rows[periods:]):
        out.append({
            "on_date": cur["on_date"],
            "index": round(cur["value"], 3),
            "change_pct": round((cur["value"] / prev["value"] - 1) * 100, 3),
            "quality": cur["quality"],
        })
    return {"frequency": frequency, "periods": periods, "series": out}


@app.get("/routes")
def routes(on: Optional[date] = Query(None)):
    """Per-route price level on a given day, for the dashboard heatmap."""
    with connect(DB_PATH) as conn:
        if on is None:
            r = conn.execute("SELECT MAX(collected_on) d FROM cell_price").fetchone()
            on = date.fromisoformat(r["d"]) if r and r["d"] else None
        if on is None:
            return {"on": None, "routes": []}
        rows = conn.execute(
            "SELECT route, advance_days, AVG(price) p, SUM(n_quotes) n "
            "FROM cell_price WHERE collected_on=? AND imputed=0 "
            "GROUP BY route, advance_days ORDER BY route, advance_days", (on.isoformat(),)
        ).fetchall()
    return {"on": on.isoformat(), "cells": [dict(r) for r in rows]}


@app.get("/compliance")
def compliance():
    """The audit, served. Which sources we collect, which we do not, and why."""
    return {
        "policy": (
            "Collection is gated on robots.txt at request time and fails closed. "
            "No CAPTCHA solving, no proxy rotation, no fingerprint spoofing. A 403, "
            "429 or bot challenge is recorded as a non-response and handled by "
            "imputation, never evaded."
        ),
        "sources": [
            {
                "id": s.id, "name": s.name, "kind": s.kind,
                "status": s.status.value, "collected": s.collectable,
                "carriers": list(s.carrier_codes), "reason": s.note,
            }
            for s in load_sources()
        ],
    }


@app.get("/collection-log")
def collection_log(limit: int = Query(200, le=2000)):
    with connect(DB_PATH) as conn:
        rows = conn.execute(
            "SELECT * FROM collection_log ORDER BY id DESC LIMIT ?", (limit,)
        ).fetchall()
    return {"n": len(rows), "entries": [dict(r) for r in rows]}


@app.get("/", response_class=HTMLResponse)
def dashboard():
    if not DASHBOARD.exists():
        raise HTTPException(404, "dashboard not built")
    return HTMLResponse(DASHBOARD.read_text())
